# app/models/concerns/cancellation_reasons.rb
module CancellationReasons
  extend ActiveSupport::Concern

  # Legacy reasons - no longer used in the BaSM frontend
  # but we keep them to ensure supplier compatibility
  CANCELLATION_REASON_MADE_IN_ERROR = 'made_in_error'.freeze
  CANCELLATION_REASON_SUPPLIER_DECLINED_TO_MOVE = 'supplier_declined_to_move'.freeze
  CANCELLATION_REASON_REJECTED = 'rejected'.freeze
  CANCELLATION_REASON_DATABASE_CORRECTION = 'database_correction'.freeze
  CANCELLATION_REASON_INCOMPLETE_PER = 'incomplete_per'.freeze
  CANCELLATION_REASON_OTHER = 'other'.freeze

  # Active reasons
  CANCELLATION_REASON_CANCELLED_BY_PMU = 'cancelled_by_pmu'.freeze
  CANCELLATION_REASON_CASE_NOT_COURT_READY = 'case_not_court_ready'.freeze
  CANCELLATION_REASON_COMBINED_WITH_ANOTHER_REQUEST = 'combined_with_another_request'.freeze
  CANCELLATION_REASON_COURT_CLOSURE = 'court_closure'.freeze
  CANCELLATION_REASON_COURT_NO_CAPACITY = 'court_no_capacity'.freeze
  CANCELLATION_REASON_COURT_NOT_DDA_COMPLIANT = 'court_not_dda_compliant'.freeze
  CANCELLATION_REASON_INCORRECT_COLLECTION_LOCATION = 'incorrect_collection_location'.freeze
  CANCELLATION_REASON_INCORRECT_FINAL_LOCATION = 'incorrect_final_location'.freeze
  CANCELLATION_REASON_LIST_RECEIVED_AFTER_5_PM = 'list_received_after_5_pm'.freeze
  CANCELLATION_REASON_OPERATIONAL_ISSUES_PRISON = 'operational_issues_prison'.freeze
  CANCELLATION_REASON_POLICE_TRANSPORTED_PRISONER = 'police_transported_prisoner'.freeze
  CANCELLATION_REASON_PRISON_TRANSPORTED_PRISONER = 'prison_transported_prisoner'.freeze
  CANCELLATION_REASON_PRISONER_REFUSAL = 'prisoner_refusal'.freeze
  CANCELLATION_REASON_PRISONER_TO_BE_RELEASED_ON_BAIL = 'prisoner_to_be_released_on_bail'.freeze
  CANCELLATION_REASON_PRISONER_UNFIT_TO_TRAVEL = 'prisoner_unfit_to_travel'.freeze
  CANCELLATION_REASON_PTR_UNACHIEVABLE = 'ptr_unachievable'.freeze
  CANCELLATION_REASON_RECEIVER_UNABLE_TO_ACCEPT_PRISONER = 'receiver_unable_to_accept_prisoner'.freeze
  CANCELLATION_REASON_SENDER_UNABLE_TO_FULFIL_DRAFT = 'sender_unable_to_fulfil_draft'.freeze
  CANCELLATION_REASON_SENDER_CANCELLED_REQUEST = 'sender_cancelled_request'.freeze
  CANCELLATION_REASON_SUPPLIER_NO_RESOURCE = 'supplier_no_resource'.freeze
  CANCELLATION_REASON_TORNADO_EVENT = 'tornado_event'.freeze
  CANCELLATION_REASON_UNSUITABLE_VEHICLE = 'unsuitable_vehicle'.freeze
  CANCELLATION_REASON_VIDEO_LINK_TO_BE_USED = 'video_link_to_be_used'.freeze

  CANCELLATION_REASONS = [
    CANCELLATION_REASON_MADE_IN_ERROR,
    CANCELLATION_REASON_SUPPLIER_DECLINED_TO_MOVE,
    CANCELLATION_REASON_REJECTED,
    CANCELLATION_REASON_DATABASE_CORRECTION,
    CANCELLATION_REASON_INCOMPLETE_PER,
    CANCELLATION_REASON_OTHER,
    CANCELLATION_REASON_CANCELLED_BY_PMU,
    CANCELLATION_REASON_CASE_NOT_COURT_READY,
    CANCELLATION_REASON_COMBINED_WITH_ANOTHER_REQUEST,
    CANCELLATION_REASON_COURT_CLOSURE,
    CANCELLATION_REASON_COURT_NO_CAPACITY,
    CANCELLATION_REASON_COURT_NOT_DDA_COMPLIANT,
    CANCELLATION_REASON_INCORRECT_COLLECTION_LOCATION,
    CANCELLATION_REASON_INCORRECT_FINAL_LOCATION,
    CANCELLATION_REASON_LIST_RECEIVED_AFTER_5_PM,
    CANCELLATION_REASON_OPERATIONAL_ISSUES_PRISON,
    CANCELLATION_REASON_POLICE_TRANSPORTED_PRISONER,
    CANCELLATION_REASON_PRISON_TRANSPORTED_PRISONER,
    CANCELLATION_REASON_PRISONER_REFUSAL,
    CANCELLATION_REASON_PRISONER_TO_BE_RELEASED_ON_BAIL,
    CANCELLATION_REASON_PRISONER_UNFIT_TO_TRAVEL,
    CANCELLATION_REASON_PTR_UNACHIEVABLE,
    CANCELLATION_REASON_RECEIVER_UNABLE_TO_ACCEPT_PRISONER,
    CANCELLATION_REASON_SENDER_UNABLE_TO_FULFIL_DRAFT,
    CANCELLATION_REASON_SENDER_CANCELLED_REQUEST,
    CANCELLATION_REASON_SUPPLIER_NO_RESOURCE,
    CANCELLATION_REASON_TORNADO_EVENT,
    CANCELLATION_REASON_UNSUITABLE_VEHICLE,
    CANCELLATION_REASON_VIDEO_LINK_TO_BE_USED,
  ].freeze
end
