inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require: rubocop-rspec

AllCops:
  # Exclude anything that isn't really part of our code.
  # rails_helper is excluded because it's full of solecisms, but it's mostly
  # generated code and copy-and-pasted snipets from READMEs.
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"

Style/Documentation:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

RSpec/NestedGroups:
  Max: 4

RSpec/LetSetup:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

# I think we disagree with GDS over this one
Style/StringLiterals:
  Enabled: false

# I think we disagree with GDS on this one too
Style/MethodCalledOnDoEndBlock:
  Enabled: false

#TODO: we have lots of these, and fixing them will create massive noise in the PR
Rails/Date:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: false