inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  # Exclude anything that isn't really part of our code.
  # rails_helper is excluded because it's full of solecisms, but it's mostly
  # generated code and copy-and-pasted snipets from READMEs.
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "tmp/**/*"

# This seems very much personal choice, and would alter every string
# if we switched to the GDS standard.
Style/StringLiterals:
  EnforcedStyle: single_quotes

# This cops seems defective. Sometimes it does not detect when the variable
# is referenced elsewhere such as in shared examples.
RSpec/LetSetup:
  Enabled: false
