inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require: rubocop-rspec

AllCops:
  # Exclude anything that isn't really part of our code.
  # rails_helper is excluded because it's full of solecisms, but it's mostly
  # generated code and copy-and-pasted snipets from READMEs.
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"

Style/Documentation:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

RSpec/NestedGroups:
  Max: 4

RSpec/LetSetup:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

# I think we disagree with GDS over this one
Style/StringLiterals:
  Enabled: false

# I think we disagree with GDS on this one too
Style/MethodCalledOnDoEndBlock:
  Enabled: false

# don't worry about timezones in tests or during fake data creation
Rails/Date:
  Exclude:
    - "lib/tasks/fake_data.rake"
    - "spec/**/**/*"

# The anonymiser isn't production code, and is going away soon
Rails/TimeZone:
  Exclude:
    - "spec/**/**/*"
    - "app/services/moves/anonymiser.rb"

# These 3 Style settings would cause a large number of changes. Do we bite the bullet now, or just agree
# to disagree with the GDS style guidelines?
Rails/HasManyOrHasOneDependent:
  Enabled: false