require: rubocop-rspec

AllCops:
  # Exclude anything that isn't really part of our code.
  # rails_helper is excluded because it's full of solecisms, but it's mostly
  # generated code and copy-and-pasted snipets from READMEs.
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"

Style/Documentation:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

RSpec/NestedGroups:
  Max: 4
