---
basePath: "/api/v1"
openapi: 3.0.1
info:
  title: PECS4 API V1 Docs
  version: v1
  description: Book A Secure Move supplier and frontend API.
consumes:
- application/vnd.api+json
servers:
- url: http://localhost:3000/api/v1
  description: Local development (localhost)
- url: https://hmpps-book-secure-move-api-staging.apps.live-1.cloud-platform.service.justice.gov.uk/api/v1
  description: Staging API
- url: https://hmpps-book-secure-move-api-preprod.apps.live-1.cloud-platform.service.justice.gov.uk/api/v1
  description: PreProd API
- url: https://api.bookasecuremove.service.justice.gov.uk/api/v1
  description: Production API
security:
- oauth2: []
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          authorizationUrl: "/oauth/authorize"
          tokenUrl: "/oauth/token/"
          scopes: {}
definitions:
  location_reference:
    LocationReference:
      type: object
      required:
      - data
      properties:
        data:
          oneOf:
          - type: object
            required:
            - id
            - type
            properties:
              type:
                type: string
                example: locations
                description: The type of this object - always `locations`
              id:
                type: string
                format: uuid
                example: 3561f372-9f1c-4e13-997e-b11e1647cce1
                description: The unique identifier (UUID) of object that this reference
                  points to
          - type: 'null'
  get_move_responses:
    '200':
      type: object
      required:
      - data
      properties:
        data:
          "$ref": "#/definitions/move/Move"
    '401':
      type: object
      required:
      - errors
      properties:
        errors:
          type: array
          items:
            "$ref": "#/definitions/errors/NotAuthorisedError"
    '404':
      type: object
      required:
      - errors
      properties:
        errors:
          type: array
          items:
            "$ref": "#/definitions/errors/ResourceNotFound"
    '415':
      type: object
      required:
      - errors
      properties:
        errors:
          type: array
          items:
            "$ref": "#/definitions/errors/UnsupportedMediaType"
  move:
    Move:
      type: object
      required:
      - id
      - type
      - attributes
      properties:
        id:
          type: string
          format: uuid
          example: f0a91e16-1b0e-4e1f-93fe-319dda9933e6
          description: The unique identifier (UUID) of this object
        type:
          type: string
          example: moves
          description: The type of this object - always `moves`
        attributes:
          type: object
          required:
          - status
          - date
          - reference
          properties:
            reference:
              type: string
              example: TM7B3A2S
              description: Unique human-readable identifier for the Move
            status:
              type: string
              enum:
              - requested
              - cancelled
              description: Indicates the stage in it's lifecycle that this move is
                at
            move_type:
              type: string
              enum:
              - court_appearance
              - prison_recall
              - prison_transfer
              description: Indicates the type of move, e.g. prison transfer or court
                appearance
            time_due:
              type: string
              format: date-time
              description: Time due at the destination, e.g. court appointment time
            updated_at:
              type: string
              format: date-time
              description: Timestamp of when the move was last created or updated
            date:
              type: string
              format: date
              example: '2019-05-24'
              description: Date on which the move is scheduled
            additional_information:
              oneOf:
              - type: string
              - type: 'null'
              description: Additional information about the move that the supplier
                should be made aware of
            cancellation_reason:
              oneOf:
              - type: string
                enum:
                - made_in_error
                - supplier_declined_to_move
                - other
              - type: 'null'
              description: Reason the move has been cancelled
            cancellation_reason_comment:
              oneOf:
              - type: string
              - type: 'null'
              description: In case 'other' is chosen as cancellation_reason, further
                details can be specified
        relationships:
          type: object
          properties:
            person:
              "$ref": "#/definitions/person_reference/PersonReference"
              description: The person being moved
            from_location:
              "$ref": "#/definitions/location_reference/LocationReference"
              description: The location that the person is being moved from
            to_location:
              "$ref": "#/definitions/location_reference/LocationReference"
              description: The location that the person is being moved to
  person_reference:
    PersonReference:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          required:
          - type
          - id
          properties:
            type:
              type: string
              example: people
              description: The type of this object - always `people`
            id:
              type: string
              format: uuid
              example: ea5ace8e-e9ad-4ca3-9977-9bf69e3b6154
              description: The unique identifier (UUID) of the object that this reference
                points to
  errors:
    BadRequest:
      type: object
      properties:
        title:
          type: string
          example: Bad request
        detail:
          type: string
          example: The server cannot or will not process the request due to an apparent
            client error
    Forbidden:
      type: object
      properties:
        title:
          type: string
          example: Forbidden
        detail:
          type: string
          example: The resource is readonly
    NotAuthorisedError:
      type: object
      properties:
        title:
          type: string
          example: Not authorized
        detail:
          type: string
          example: Token expired or invalid
    ResourceNotFound:
      type: object
      properties:
        title:
          type: string
          example: Resource not found
        detail:
          type: string
          example: The requested resource was not found
    UnsupportedMediaType:
      type: object
      properties:
        title:
          type: string
          example: Invalid Media Type
        detail:
          type: string
          example: Content-Type must be application/vnd.api+json
    UnprocessableEntity:
      type: object
      properties:
        title:
          type: string
          example: Unprocessable entity
        code:
          type: string
          example: validation_error
        detail:
          type: string
          example: The request was well-formed but was unable to be followed due to
            semantic errors
        source:
          type: object
          properties:
            pointer:
              type: string
              example: "/data/attributes/property"
  error_responses:
    '401':
      type: object
      required:
      - errors
      properties:
        errors:
          type: array
          items:
            "$ref": "#/definitions/errors/NotAuthorisedError"
    '404':
      type: object
      required:
      - errors
      properties:
        errors:
          type: array
          items:
            "$ref": "#/definitions/errors/ResourceNotFound"
    '415':
      type: object
      required:
      - errors
      properties:
        errors:
          type: array
          items:
            "$ref": "#/definitions/errors/UnsupportedMediaType"
paths:
  "/moves/{moveId}":
    get:
      summary: Returns the details of a move
      tags:
      - Moves
      produces:
      - application/vnd.api+json
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
          default: Bearer <your-client-token>
        required: true
        description: |
          This is "Bearer ", followed by your OAuth 2 Client token.
          If you're testing interactively in the web UI, you can ignore this field
      - name: Content-Type
        in: header
        description: Accepted request content type
        schema:
          type: string
          default: application/vnd.api+json
        required: true
      - name: moveId
        in: path
        description: The ID of the move
        schema:
          type: string
        format: uuid
        example: 00525ecb-7316-492a-aae2-f69334b2a155
        required: true
      responses:
        '401':
          description: unauthorised
          schema:
            "$ref": "#/definitions/error_responses/401"
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/definitions/error_responses/401"
          examples:
            application/vnd.api+json:
              errors:
              - title: Not authorized
                detail: Token expired or invalid
        '415':
          description: invalid content type
          schema:
            "$ref": "#/definitions/error_responses/415"
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/definitions/error_responses/415"
          examples:
            application/vnd.api+json:
              errors:
              - title: Invalid Media Type
                detail: Content-Type must be application/vnd.api+json
        '404':
          description: not found
          schema:
            "$ref": "#/definitions/error_responses/404"
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/definitions/error_responses/404"
          examples:
            application/vnd.api+json:
              errors:
              - title: Resource not found
                detail: Couldn't find Move with 'id'=35ed4262-ee74-4012-a693-b822fd81a784
        '200':
          description: success
          schema:
            "$ref": "#/definitions/get_move_responses/200"
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/definitions/get_move_responses/200"
          examples:
            application/vnd.api+json:
              data:
                id: 2aa3951d-faad-4ec6-aab2-137af7065173
                type: moves
                attributes:
                  reference: FTH2347Y
                  status: requested
                  updated_at: '2020-01-03T14:27:49+00:00'
                  time_due: '2020-01-03T14:27:49+00:00'
                  date: '2020-01-03'
                  move_type: court_appearance
                  additional_information: some more info about the move that the supplier
                    might need to know
                  cancellation_reason: 
                  cancellation_reason_comment: 
                relationships:
                  person:
                    data:
                      id: 6d8c293a-460b-484b-95cb-73b808ea92ba
                      type: people
                  from_location:
                    data:
                      id: 23bb72c5-be3e-4885-844a-16bec8f8f9ae
                      type: locations
                  to_location:
                    data:
                      id: a1a33ec6-bd6e-4140-8f50-dab726d9afe5
                      type: locations
                  documents:
                    data: []
              included:
              - id: 6d8c293a-460b-484b-95cb-73b808ea92ba
                type: people
                attributes:
                  first_names: Bob
                  last_name: Roberts
                  date_of_birth: '1980-10-20'
                  assessment_answers: []
                  identifiers:
                  - identifier_type: police_national_computer
                    value: AB/1234567
                  gender_additional_information: 
                relationships:
                  ethnicity:
                    data:
                      id: f0cf8818-71e6-46c9-8fbc-37cd653ab921
                      type: ethnicities
                  gender:
                    data:
                      id: bc07e09c-923b-4f01-82b8-f2b220316f59
                      type: genders
              - id: f0cf8818-71e6-46c9-8fbc-37cd653ab921
                type: ethnicities
                attributes:
                  key: w1
                  title: White British
                  description: W1 - White British
                  nomis_code: W1
                  disabled_at: 
              - id: bc07e09c-923b-4f01-82b8-f2b220316f59
                type: genders
                attributes:
                  key: female
                  title: Female
                  description: 
                  disabled_at: 
                  nomis_code: F
              - id: 23bb72c5-be3e-4885-844a-16bec8f8f9ae
                type: locations
                attributes:
                  key: hmp_pentonville
                  title: HMP Pentonville
                  location_type: prison
                  nomis_agency_id: PEI
                  disabled_at: 
                  suppliers: []
              - id: a1a33ec6-bd6e-4140-8f50-dab726d9afe5
                type: locations
                attributes:
                  key: guildford_crown_court
                  title: Guildford Crown Court
                  location_type: court
                  nomis_agency_id: GUICCT
                  disabled_at: 
                  suppliers: []
