{{- $fullName := printf "%s-%s" (include "generic-service.fullname" $) "drop-temp-tables" | trunc 52 }}
{{- if .Values.scripts.preprodRefresh.main.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
data:
  dropTables.sql: |-
    BEGIN;
    DROP TABLE IF EXISTS framework_flags_temp CASCADE;
    DROP TABLE IF EXISTS framework_nomis_codes_temp CASCADE;
    DROP TABLE IF EXISTS framework_nomis_mappings_temp CASCADE;
    DROP TABLE IF EXISTS framework_questions_temp CASCADE;
    DROP TABLE IF EXISTS framework_responses_temp CASCADE;
    DROP TABLE IF EXISTS frameworks_temp CASCADE;
    DROP TABLE IF EXISTS framework_flags_responses_temp CASCADE;
    DROP TABLE IF EXISTS framework_nomis_codes_questions_temp CASCADE;
    DROP TABLE IF EXISTS framework_nomis_mappings_responses_temp CASCADE;
    DROP TABLE IF EXISTS locations_temp CASCADE;
    DROP TABLE IF EXISTS moves_temp CASCADE;
    DROP TABLE IF EXISTS journeys_temp CASCADE;
    DROP TABLE IF EXISTS people_temp CASCADE;
    DROP TABLE IF EXISTS profiles_temp CASCADE;
    DROP TABLE IF EXISTS person_escort_records_temp CASCADE;
    DROP TABLE IF EXISTS court_hearings_temp CASCADE;
    DROP TABLE IF EXISTS allocation_complex_cases_temp CASCADE;
    DROP TABLE IF EXISTS allocations_temp CASCADE;
    DROP TABLE IF EXISTS assessment_questions_temp CASCADE;
    DROP TABLE IF EXISTS categories_temp CASCADE;
    DROP TABLE IF EXISTS documents_temp CASCADE;
    DROP TABLE IF EXISTS ethnicities_temp CASCADE;
    DROP TABLE IF EXISTS genders_temp CASCADE;
    DROP TABLE IF EXISTS locations_regions_temp CASCADE;
    DROP TABLE IF EXISTS nomis_alerts_temp CASCADE;
    DROP TABLE IF EXISTS notifications_temp CASCADE;
    DROP TABLE IF EXISTS populations_temp CASCADE;
    DROP TABLE IF EXISTS regions_temp CASCADE;
    DROP TABLE IF EXISTS subscriptions_temp CASCADE;
    DROP TABLE IF EXISTS supplier_locations_temp CASCADE;
    DROP TABLE IF EXISTS suppliers_temp CASCADE;
    DROP TABLE IF EXISTS youth_risk_assessments_temp CASCADE;
    DROP TABLE IF EXISTS generic_events_temp CASCADE;
    DROP TABLE IF EXISTS versions_temp CASCADE;
    COMMIT;
{{- end }}
