{{- $genericService := index .Values "generic-service" -}}
{{- $fullName := printf "%s-%s" (include "generic-service.fullname" $) "preprod-refresh" | trunc 52 }}
{{- $script1 := printf "%s-%s" (include "generic-service.fullname" $) "create-temp-tables" | trunc 52 }}
{{- $script2 := printf "%s-%s" (include "generic-service.fullname" $) "copy-from-temp-sql" | trunc 52 }}
{{- $script3 := printf "%s-%s" (include "generic-service.fullname" $) "drop-temp-tables" | trunc 52 }}
{{- $script4 := printf "%s-%s" (include "generic-service.fullname" $) "preprod-refresh-script" | trunc 52 }}
{{- if .Values.scripts.preprodRefresh.main.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $fullName }}
spec:
  schedule: {{ .Values.scripts.preprodRefresh.main.schedule }}
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600
      backoffLimit: 0
      activeDeadlineSeconds: 7200
      template:
        spec:
          serviceAccountName: "book-a-secure-move-api"
          containers:
            - name: preprod-refresh
              image: "ghcr.io/ministryofjustice/hmpps-devops-tools:latest"
              command:
                - /bin/entrypoint.sh
              volumeMounts:
                - name: create-temp-tables
                  mountPath: /tmp/sql/createTables.sql
                  readOnly: true
                  subPath: createTables.sql
                - name: copy-from-temp-sql
                  mountPath: /tmp/sql/copyFromTemp.sql
                  readOnly: true
                  subPath: copyFromTemp.sql
                - name: drop-temp-tables
                  mountPath: /tmp/sql/dropTables.sql
                  readOnly: true
                  subPath: dropTables.sql
                - name: preprod-refresh-script
                  mountPath: /bin/entrypoint.sh
                  readOnly: true
                  subPath: entrypoint.sh
              env:
                - name: DEST_DB_INSTANCE
                  valueFrom:
                    secretKeyRef:
                      name: preprod-rds-creds
                      key: url
                - name: SOURCE_DB_INSTANCE
                  valueFrom:
                    secretKeyRef:
                      name: rds-instance-hmpps-book-secure-move-api-production
                      key: url
                - name: AWS_DEFAULT_REGION
                  value: "eu-west-2"
          restartPolicy: "Never"
          volumes:
            - name: create-temp-tables
              configMap:
                name: {{ $script1 }}
                defaultMode: 0755
            - name: copy-from-temp-sql
              configMap:
                name: {{ $script2 }}
                defaultMode: 0755
            - name: drop-temp-tables
              configMap:
                name: {{ $script3 }}
                defaultMode: 0755
            - name: preprod-refresh-script
              configMap:
                name: {{ $script4 }}
                defaultMode: 0755
{{- end }}
