{{- $genericService := index .Values "generic-service" -}}
{{- $fullName := printf "%s-%s" (include "generic-service.fullname" $) "preprod-refresh-versions" | trunc 52 }}
{{- $script1 := printf "%s-%s" (include "generic-service.fullname" $) "preprod-refresh-versions-script" | trunc 52 }}
{{- if .Values.scripts.preprodRefresh.versions.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $fullName }}
spec:
  schedule: {{ .Values.scripts.preprodRefresh.versions.schedule }}
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600
      backoffLimit: 0
      activeDeadlineSeconds: 7200
      template:
        spec:
          serviceAccountName: "book-a-secure-move-api"
          containers:
            - name: preprod-versions-refresh
              image: "ghcr.io/ministryofjustice/hmpps-devops-tools:latest"
              command:
                - /bin/entrypoint.sh
              volumeMounts:
                - name: preprod-refresh-versions-script
                  mountPath: /bin/entrypoint.sh
                  readOnly: true
                  subPath: entrypoint.sh
              env:
                - name: DEST_DB_INSTANCE
                  valueFrom:
                    secretKeyRef:
                      name: preprod-rds-creds
                      key: url
                - name: SOURCE_DB_INSTANCE
                  valueFrom:
                    secretKeyRef:
                      name: rds-instance-hmpps-book-secure-move-api-production
                      key: url
                - name: AWS_DEFAULT_REGION
                  value: "eu-west-2"
          restartPolicy: "Never"
          volumes:
            - name: preprod-refresh-versions-script
              configMap:
                name: {{ $script1 }}
                defaultMode: 0755
{{- end }}
