default: &default
  adapter: postgresql
  username: <%= ENV["DB_USERNAME"] %>
  host: localhost
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 6 %>

development:
  <<: *default
  database: pecs_move_platform_backend_development
test:
  <<: *default
  database: pecs_move_platform_backend_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  primary_replica:
    <<: *default
    url: <%= ENV['REPLICA_DATABASE_URL'] %>
    replica: true
