default: &default
  adapter: postgresql
  username: <%= ENV["DB_USERNAME"] %>
  host: localhost
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 6 %>

development:
  <<: *default
  database: pecs_staging
test:
  <<: *default
  database: pecs_move_platform_backend_test
