# Configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: false
:concurrency: <%= ENV['SIDEKIQ_PROCESSES'] || ENV['RAILS_MAX_THREADS'] || 3 %>
:timeout: 25

:queues:
  - notifications
  - default
