# Configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: false
:concurrency: <%= ENV['SIDEKIQ_PROCESSES'] || ENV['RAILS_MAX_THREADS'] || 3 %>
:timeout: 25

:queues:
  - ["notifications_high", 4]
  - ["notifications_medium", 3]
  - ["notifications_low", 2]
  - ["notifications", 1] # TODO: this queue can be deleted in a future PR once high/medium/low are in place
  - ["default", 1]
