test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

staging:
  service: amazon

preprod:
  service: amazon

production:
  service: amazon

amazon:
  service: S3
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
  region: 'eu-west-2'
  bucket: <%= ENV['S3_BUCKET_NAME'] %>
