{{- $fullName := printf "%s-%s" (include "generic-service.fullname" $) "weekly-cancelled-court-moves-config" | trunc 52 }}
{{- if .Values.scripts.reports.weeklyCanCourtMoves.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
data:
  from-date: "7 days ago"
  to-date: "1 day ago"
  subject: "BaSM Cancelled Court Moves Report [TODAY_DATE]"
  body: "BaSM Cancelled Court Moves report for last week ([FROM_DATE_FULL] to [TO_DATE_FULL]) is available at the link below."
  filename: "basm-cancelled-court-moves-report-[TODAY_DATE]"
  retention: "1 week"
  confirm_email: "true"
  report_sql: |-
    SELECT m.status,
      m.reference,
      m.move_type,
      m.date,
      f.title AS FROM_loc,
      t.title AS to_loc,
      COALESCE(person.nomis_prison_number, person.prison_number) AS prison_number,
      COALESCE(person.last_name, '(Allocation)') AS last_name,
      m.created_at,
      m.updated_at,
      m.cancellation_reason,
      m.cancellation_reason_comment,
      e.created_at AS cancelled_at, e.created_by AS cancelled_by,
      (SELECT EXISTS
        (select * FROM journeys where move_id = m.id AND billable = true limit 1)::boolean)
          AS journey_billable,
      beforeafter((m.date::timestamp + interval '6 hours') - e.created_at) AS difference,
      s.name AS journey_supplier

    FROM moves m
      LEFT JOIN profiles pro ON m.profile_id = pro.id
      LEFT JOIN person_escort_records per ON pro.id = per.profile_id
      LEFT JOIN people person ON  pro.person_id = person.id
      LEFT JOIN locations f ON  m.FROM_location_id = f.id
      LEFT JOIN locations t ON  m.to_location_id = t.id
      LEFT JOIN generic_events e ON e.eventable_type = 'Move'
        AND e.eventable_id = m.id AND type = 'GenericEvent::MoveCancel'
      LEFT JOIN suppliers s ON m.supplier_id = s.id

    WHERE m.date between '[FROM]' and '[TO]'
      AND m.status = 'cancelled'
      AND m.move_type = 'court_appearance'

    ORDER BY date, last_name, prison_number
{{- end }}
