{{- $fullName := printf "%s-%s" (include "generic-service.fullname" $) "weekly-cancelled-court-moves-config" | trunc 52 }}
{{- if .Values.scripts.reports.weeklyCanCourtMoves.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
data:
  from-date: "7 days ago"
  to-date: "1 day ago"
  subject: "BaSM Cancelled Court Moves Report [TODAY_DATE]"
  body: "BaSM Cancelled Court Moves report for yesterday ([FROM_DATE_FULL]) to [TO_DATE_FULL] is available at the link below."
  filename: "basm-cancelled-court-moves-report-[TODAY_DATE]"
  retention: "1 week"
  confirm_email: "true"
  recipients: {{ .Values.scripts.reports.weeklyCanCourtMoves.recipients }}
  report_sql: |-
      select m.status, 
        m.reference, 
        m.move_type, 
        m.date, 
        f.title as from_loc, 
        t.title as to_loc, 
        COALESCE(person.nomis_prison_number, person.prison_number) as prison_number,

        COALESCE(person.last_name, '(Allocation)') as last_name,
        m.created_at,
        m.updated_at,
        m.cancellation_reason,
        m.cancellation_reason_comment,
        e.created_at as cancelled_at, e.created_by as cancelled_by,
        j.billable as journey_billable,
        beforeafter((m.date::timestamp +  interval '6 hours') - e.created_at) as difference,
        s.name as journey_supplier
        from moves m 
          left join profiles pro on m.profile_id = pro.id
        left join person_escort_records per on pro.id = per.profile_id
        left join people person on  pro.person_id = person.id
        left join locations f on  m.from_location_id = f.id
        left join locations t on  m.to_location_id = t.id
        left join generic_events e on e.eventable_type = 'Move' and e.eventable_id = m.id and type = 'GenericEvent::MoveCancel'
        left join journeys j on j.move_id = m.id 
        left join suppliers s on j.supplier_id = s.id 
      where m.date between '[FROM]' and '[TO]' 
      and m.status = 'cancelled' 
      and m.move_type = 'court_appearance'
      order by date, last_name, prison_number
{{- end }}
