class AddUsernamePasswordToSubscription < ActiveRecord::Migration[5.2]
  def change
    # NB: encrypted string is a string and not a binary field (generated by ActiveSupport::MessageEncryptor)
    add_column :subscriptions, :encrypted_username, :string
    add_column :subscriptions, :encrypted_password, :string
  end
end
