class CreateSubscriptions < ActiveRecord::Migration[5.2]
  def change
    create_table :subscriptions, id: :uuid do |t|
      t.references :supplier, foreign_key: true, null: false, type: :uuid
      t.string :callback_url, null: false, index: true
      # TODO: consider adding a topic or filter field to limit subscriptions in the future
      # NB: no username or password for now: see p.18 of https://docs.google.com/document/d/1uyACaRNgVkCNje1szDiPQrkq7Vys5MGOUq0YJ9qB0QU/edit#heading=h.vtp2e5i3xqxm
      # NB: encrypted string is a string and not a binary field (generated by ActiveSupport::MessageEncryptor)
      t.string :encrypted_secret
      t.boolean :enabled, null: false, default: true

      t.timestamps
    end
  end
end
