---
# Per environment values which override defaults in hmpps-book-secure-move-api/values.yaml

buildEnv: uat

generic-service:
  replicaCount: 2

  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/set-identifier: hmpps-book-secure-move-api-v1-2-hmpps-book-secure-move-api-uat-green
      nginx.ingress.kubernetes.io/server-snippet: add_header X-Robots-Tag "noindex, nofollow";
    hosts:
      - hmpps-book-secure-move-api-uat.apps.cloud-platform.service.justice.gov.uk

  env:
    SENTRY_ENVIRONMENT: "uat"
    SERVER_FQDN: "hmpps-book-secure-move-api-uat.apps.cloud-platform.service.justice.gov.uk"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]
  namespace_secrets:
    hmpps-book-secure-move-api-secrets-uat:
      SECRET_KEY_BASE: secret_key_base_key
      NOMIS_SITE: nomis_site_key
      NOMIS_SITE_FOR_API: nomis_site_for_api_key
      NOMIS_SITE_FOR_AUTH: nomis_site_for_auth_key
      NOMIS_CLIENT_ID: nomis_client_id_key
      NOMIS_CLIENT_SECRET: nomis_client_secret_key
      NOMIS_AUTH_SCHEME: nomis_auth_scheme_key
      NOMIS_API_PATH_PREFIX: nomis_api_path_prefix_key
      NOMIS_PRISON_API_PATH_PREFIX: nomis_prison_api_path_prefix_key
      NOMIS_AUTH_PATH_PREFIX: nomis_auth_path_prefix_key
      ALERTS_API_BASE_URL: alerts_api_base_url_key
      SENTRY_DSN: sentry_dsn_key
      CORS_ALLOWED_ORIGINS: cors_allowed_origins_key
      ENCRYPTOR_SALT: encryptor_salt
    rds-instance-hmpps-book-secure-move-api-uat:
      DATABASE_URL: url
    book-a-secure-move-documents-s3-bucket:
      S3_BUCKET_ARN: bucket_arn
      S3_BUCKET_NAME: bucket_name
    book-a-secure-move-metrics-s3-bucket:
      S3_METRICS_BUCKET_NAME: bucket_name
    elasticache-hmpps-book-secure-move-api-uat:
      REDIS_URL: url

sidekiq:
  overrideValues:
    namespace_secrets:
      hmpps-book-secure-move-api-secrets-uat:
        GOVUK_NOTIFY_API_KEY: govuk_notify_api_key

cronJobs:
  - name: access-log-cleanup
    schedule: "0 2 * * *"
    command: ["bundle", "exec", "rake", "access_logs:cleanup"]
  - name: token-cleanup
    schedule: "0 1 * * 0"
    command: ["bundle", "exec", "rake", "doorkeeper:db:cleanup"]
  - name: metrics
    schedule: "*/30 * * * *"
    command: ["bundle", "exec", "rake", "metrics:export"]
    overrideValues:
      env:
        S3_METRICS_REGION: "eu-west-2"
      namespace_secrets:
        book-a-secure-move-metrics-s3-bucket:
          S3_METRICS_BUCKET_NAME: bucket_name