---
# Per environment values which override defaults in hmpps-book-secure-move-api/values.yaml

buildEnv: preprod

generic-service:
  replicaCount: 2

  ingress:
    external-dns.alpha.kubernetes.io/set-identifier: hmpps-book-secure-move-api-ingress-preprod-hmpps-book-secure-move-api-preprod-green
    hosts:
      - hmpps-book-secure-move-api-preprod.apps.live-1.cloud-platform.service.justice.gov.uk
      - hmpps-book-secure-move-api-preprod.apps.cloud-platform.service.justice.gov.uk

  env:
    ENCRYPTOR_SALT: '\xA7\xFD\xD1\xEAfu*hk\xE8\xD4Gi\xF0@:\xD1\x0Ew\xEC\xB7\xCF\xF4\xD9\xB3\xA9,\x8D\a,\x19\xEC'
    SENTRY_ENVIRONMENT: "preprod"
    SERVE_API_DOCS: "false"
    SERVER_FQDN: "hmpps-book-secure-move-api-preprod.apps.cloud-platform.service.justice.gov.uk"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]
  namespace_secrets:
    hmpps-book-secure-move-api-secrets-preprod:
      SECRET_KEY_BASE: secret_key_base_key
      NOMIS_SITE: nomis_site_key
      NOMIS_SITE_FOR_API: nomis_site_for_api_key
      NOMIS_SITE_FOR_AUTH: nomis_site_for_auth_key
      NOMIS_CLIENT_ID: nomis_client_id_key
      NOMIS_CLIENT_SECRET: nomis_client_secret_key
      NOMIS_AUTH_SCHEME: nomis_auth_scheme_key
      NOMIS_API_PATH_PREFIX: nomis_api_path_prefix_key
      NOMIS_PRISON_API_PATH_PREFIX: nomis_prison_api_path_prefix_key
      NOMIS_AUTH_PATH_PREFIX: nomis_auth_path_prefix_key
      SENTRY_DSN: sentry_dsn_key
      CORS_ALLOWED_ORIGINS: cors_allowed_origins_key
      PER_QUALITY_REPORT_RECIPIENTS: per_quality_report_recipients
    rds-instance-hmpps-book-secure-move-api-preprod:
      DATABASE_URL: url
    book-a-secure-move-documents-s3-bucket:
      S3_ACCESS_KEY_ID: access_key_id
      S3_SECRET_ACCESS_KEY: secret_access_key
      S3_BUCKET_ARN: bucket_arn
      S3_BUCKET_NAME: bucket_name
    book-a-secure-move-metrics-s3-bucket:
      S3_METRICS_ACCESS_KEY_ID: access_key_id
      S3_METRICS_SECRET_ACCESS_KEY: secret_access_key
      S3_METRICS_REGION: "eu-west-2"
      S3_METRICS_BUCKET_NAME: bucket_name
    elasticache-hmpps-book-secure-move-api-preprod:
      REDIS_URL: url

cronJobs:
  - name: token-cleanup
    schedule: "0 1 * * 0"
    command: ["bundle", "exec", "rake", "doorkeeper:db:cleanup"]
  - name: metrics
    suspend: true
    schedule: "*/30 * * * *"
    command: ["bundle", "exec", "rake", "metrics:export"]
    overrideValues:
      env:
        S3_METRICS_REGION: "eu-west-2"
      namespace_secrets:
        book-a-secure-move-metrics-s3-bucket:
          S3_METRICS_ACCESS_KEY_ID: access_key_id
          S3_METRICS_SECRET_ACCESS_KEY: secret_access_key
          S3_METRICS_BUCKET_NAME: bucket_name