{{- $fullName := printf "%s-%s" (include "generic-service.fullname" $) "automated-reports-scripts" | trunc 52 }}
{{- if .Values.scripts.reports.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
data:
  notify-token.sh: |-
    #!/bin/bash
    iss=$(echo ${NOTIFY_TOKEN} | awk -F '-' '{print $2"-"$3"-"$4"-"$5"-"$6 }')
    secret=$(echo ${NOTIFY_TOKEN} | awk -F '-' '{print $7"-"$8"-"$9"-"$10"-"$11 }')
    
    # Create JWT for Notify
    header=$(echo -n '{"alg":"HS256","typ":"JWT"}' | openssl base64 -e -A | tr '+/' '-_' | tr -d '=')
    current_time=$(date +%s)
    payload=$(echo -n "{\"iss\":\"${iss}\",\"iat\":\"${current_time}\"}" | openssl base64 -e -A | tr '+/' '-_' | tr -d '=')
    signature=$(echo -n "$header.$payload" | openssl dgst -sha256 -hmac "${secret}" -binary | openssl base64 -e -A | tr '+/' '-_' | tr -d '=')
    # JWT
    jwt="$header.$payload.$signature"
    
    echo "${jwt}"

  run-report.sh: |-
    FROM_DATE=$(date --date="$REPORT_START" '+%Y-%m-%d')
    FROM_DATE_FULL=$(date --date="$REPORT_START" '+%A, %e %B')
    TO_DATE=$(date --date="$REPORT_END" '+%Y-%m-%d')
    TO_DATE_FULL=$(date --date="$REPORT_END" '+%A, %e %B')
    TODAY_DATE=$(date '+%Y-%m-%d')
    TODAY_FULL=$(date '+%A, %e %B')
  
    echo "Report start date: $FROM_DATE ($REPORT_START)"
    echo "Report end date: $TO_DATE ($REPORT_END)"
    cp /report/report.sql /tmp/report.sql
    echo "Replacing start and end date placeholders in template SQL"
    
    sed -i '/tmp/report.sql' -e "s/\[FROM\]/${FROM_DATE}/g"
    sed -i '/tmp/report.sql' -e "s/\[TO\]/${TO_DATE}/g" 
    echo -n  ' \COPY (' > /tmp/cmd.sql
    echo -n $(tr '\n' ' ' < /tmp/report.sql) >> /tmp/cmd.sql
    echo -n ") TO '/tmp/out.csv' csv header;" >> /tmp/cmd.sql
    
    echo "Querying the database"
    psql $DB_INSTANCE -f /tmp/cmd.sql
    
    echo "CSV created - $(wc -l /tmp/out.csv | awk '{print $1}') lines"
    echo "Base64 encoding..."
    b64=$(base64 -i /tmp/out.csv)
    echo "Base64 encoding complete"
    
    notify='api.notifications.service.gov.uk/v2/notifications/email'
    
    echo ${EMAIL_BODY} > /tmp/body.txt
    echo ${EMAIL_SUBJECT} > /tmp/subject.txt
    echo ${FILENAME}.csv > /tmp/filename.txt
    INPUT='/tmp/body.txt' REPORT_START="${REPORT_START}" REPORT_END="${REPORT_END}" /scripts/placeholders.sh
    INPUT='/tmp/subject.txt' REPORT_START="${REPORT_START}" REPORT_END="${REPORT_END}" /scripts/placeholders.sh
    INPUT='/tmp/filename.txt' REPORT_START="${REPORT_START}" REPORT_END="${REPORT_END}" /scripts/placeholders.sh
        
    for i in ${EMAIL_ADDRESSEES//,/ }
    do
    
    https --timeout 30 --ignore-stdin  -A bearer -a $(bash /scripts/notify-token.sh) $notify \
    email_address="$i" \
    template_id='e8b1811b-e02f-4fe3-bddc-5f240965c789' \
    personalisation[main-text]="$(cat /tmp/body.txt)" \
    personalisation[email-subject]="$(cat /tmp/subject.txt).csv" \
    personalisation[link_to_file][file]="@/tmp/report.b64" \
    personalisation[link_to_file][filename]="$(cat /tmp/filename.txt)" \
    personalisation[link_to_file][confirm_email_before_download]:=${CONFIRM_EMAIL} \
    personalisation[link_to_file][retention_period]="${RETENTION_PERIOD}"
    
    done

  placeholders: |-
    FROM_DATE=$(date --date="$REPORT_START" '+%Y-%m-%d')
    FROM_DATE_FULL=$(date --date="$REPORT_START" '+%A, %e %B')
    TO_DATE=$(date --date="$REPORT_END" '+%Y-%m-%d')
    TO_DATE_FULL=$(date --date="$REPORT_END" '+%A, %e %B')
    TODAY_DATE=$(date '+%Y-%m-%d')
    TODAY_FULL=$(date '+%A, %e %B')
    
    sed -i ${INPUT} -e "s/\[FROM_DATE\]/${FROM_DATE}/g"
    sed -i ${INPUT} -e "s/\[FROM_DATE_FULL\]/${FROM_DATE_FULL}/g" 
    sed -i ${INPUT} -e "s/\[TO_DATE\]/${TO_DATE}/g"
    sed -i ${INPUT} -e "s/\[TO_DATE_FULL\]/${TO_DATE_FULL}/g"
    sed -i ${INPUT} -e "s/\[TODAY_DATE\]/${TODAY_DATE}/g"
    sed -i ${INPUT} -e "s/\[TODAY_FULL\]/${TODAY_FULL}/g"
{{- end }}
