name: Pipeline [test -> build]

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  packages: write

concurrency:
  # if branch is main, append commit sha to the group name, so that other jobs from main don't get cancelled
  group: ${{ github.workflow }}-${{ github.ref }}${{ (github.ref == 'refs/heads/main') && format('-{0}', github.sha) || '' }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: Build ruby
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: Setup Ruby and install gems
      uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1
      with:
        bundler-cache: true
  helm_lint:
    strategy:
      matrix:
        environments: ['staging', 'uat', 'preprod', 'production']
    name: Helm lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: ${{ matrix.environments }}
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    env:
      BUNDLER_VERSION: 2.6.9
      RAILS_ENV: test
      RACK_ENV: test
      DATABASE_URL: "postgres://postgres:postgres@localhost/hmpps-book-secure-move-api"
      EXTERNAL_URL: mocked_in_tests
      ENCRYPTOR_SALT: "2EREZ8Xub/vt0ya1ZM6YKUwIMN72MbmqeWMq7KS4BV8oSJJc27rDpZYmA6AQGYcS"
      EXTERNAL_WIREMOCK: "true"
    services:
      postgres:
        image: postgres:16.14-alpine
        env:
          POSTGRES_DB: hmpps-book-secure-move-api
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Get wiremock
        shell: bash
        run: |
          curl --fail --retry 2 -o wiremock.jar https://repo1.maven.org/maven2/org/wiremock/wiremock-standalone/3.9.2/wiremock-standalone-3.9.2.jar
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1
        with:
          bundler-cache: true
      - name: Setup test database
        run: bundle exec rake db:prepare RAILS_ENV=test
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run wiremock
        run: |
          nohup java -jar wiremock.jar --port 8888 &
          sleep 5
      - name: Run rspec
        run: |
          bundle exec rspec

