name: Security OWASP dependency check

on:
  workflow_call:
    inputs:
      channel_id:
        description: 'The slack channel ID to send a message on failure. If this is not provided then no message is sent.'
        required: false
        default: 'NO_SLACK'
        type: string
      subproject:
        description: 'For gradle multi module projects, leave blank for single module projects'
        required: false
        default: ''
        type: string
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN:
        description: 'Slack bot token'
        required: false

permissions:
  contents: read

jobs:
  security-owasp-check:
    name: Security OWASP dependency check
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Run gradle OWASP Dependency Check Analyse
      id: owasp-analyse
      run: ./gradlew ${{ inputs.subproject }}:dependencyCheckAnalyze --info
      continue-on-error: true
    - uses: github/codeql-action/upload-sarif@v3
      id: owasp-upload-sarif
      with:
        sarif_file: ${{ inputs.subproject == '' && '.' || inputs.subproject }}/build/reports/dependency-check-report.sarif
        category: gradle-owasp-dependency-check
    - uses: actions/upload-artifact@v4
      id: owasp-upload-artifact
      with:
        name: gradle-owasp-dependency-check-${{ inputs.subproject == '' && github.event.repository.name || inputs.subproject }}
        path: ${{ inputs.subproject == '' && '.' || inputs.subproject }}/build/reports/dependency-check-report.html
    - name: Gradle OWASP slack notification
      uses: ministryofjustice/hmpps-github-actions/.github/actions/slack_codescan_notification@v0.5 # WORKFLOW_VERSION
      if: (failure() || steps.owasp-analyse.outcome == 'failure') && inputs.channel_id != 'NO_SLACK'
      with:
        title: "Gradle OWASP"
        warningOnly: ${{ steps.owasp-upload-sarif.outcome == 'success' && steps.owasp-upload-artifact.outcome == 'success' }}
        channel_id: ${{ inputs.channel_id}}
        SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
        subproject: ${{ inputs.subproject }}