name: Security veracode policy scan

on:
  workflow_call:
    inputs:
      channel_id:
        required: false
        default: 'NO_SLACK'
        type: string
      teams:
        required: false
        type: string
        default: "hmpps-tech"
        description: "Comma-separated list of team names associated with the specified application.  Validates against the names of existing teams for this account."
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN:
        description: Slack bot token
        required: false
      HMPPS_VERACODE_API_ID_0:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_ID_1:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_ID_2:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_ID_3:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_ID_4:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_KEY_0:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_KEY_1:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_KEY_2:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_KEY_3:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_KEY_4:
        description: Veracode app secret
        required: true

permissions:
  contents: read

jobs:
  security-veracode-policy-scan:
    name: Security veracode policy scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    env:
      docker_image_app_dir: "/app"
      additional_docker_build_args: ""
      jdk_tag: "17.0"
      java_options: "-Xmx1024m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process"

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: prepare assets
      uses: ministryofjustice/hmpps-github-actions/.github/actions/security_veracode_prepare_artifacts@v0.5 # WORKFLOW_VERSION
    - name: "Download/Extract veracode agent"
      run: wget https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/22.9.10.3/vosp-api-wrappers-java-22.9.10.3.jar -O VeracodeJavaAPI.jar
    - name: "Upload to Veracode"
      shell: bash
      run: |
          echo "Randomly picking 1 of 5 api keys, to help avoid veracode API rate limits."
          X=$(( RANDOM % 4 ))
          VERACODE_API_ID_X="VERACODE_API_ID_${X}"
          VERACODE_API_KEY_X="VERACODE_API_KEY_${X}"
          VERACODE_API_ID="${!VERACODE_API_ID_X}"
          VERACODE_API_KEY="${!VERACODE_API_KEY_X}"
          echo "Using VERACODE_API_ID_${X} from pool (${VERACODE_API_ID:0:5}...)"
          java -jar VeracodeJavaAPI.jar \
          -vid "${VERACODE_API_ID}" \
          -vkey "${VERACODE_API_KEY}" \
          -teams "${{ inputs.teams }}" \
          -action UploadAndScan \
          -appname ${{ github.event.repository.name }} \
          -createprofile true \
          -deleteincompletescan 2 \
          -version "GITHUB-${{ github.run_id}}" \
          -filepath source.zip \
          2>&1 | tee output.txt
#      continue-on-error: true
      env:
        VERACODE_API_ID_0: ${{ secrets.HMPPS_VERACODE_API_ID_0 }}
        VERACODE_API_ID_1: ${{ secrets.HMPPS_VERACODE_API_ID_1 }}
        VERACODE_API_ID_2: ${{ secrets.HMPPS_VERACODE_API_ID_2 }}
        VERACODE_API_ID_3: ${{ secrets.HMPPS_VERACODE_API_ID_3 }}
        VERACODE_API_ID_4: ${{ secrets.HMPPS_VERACODE_API_ID_4 }}
        VERACODE_API_KEY_0: ${{ secrets.HMPPS_VERACODE_API_KEY_0 }}
        VERACODE_API_KEY_1: ${{ secrets.HMPPS_VERACODE_API_KEY_1 }}
        VERACODE_API_KEY_2: ${{ secrets.HMPPS_VERACODE_API_KEY_2 }}
        VERACODE_API_KEY_3: ${{ secrets.HMPPS_VERACODE_API_KEY_3 }}
        VERACODE_API_KEY_4: ${{ secrets.HMPPS_VERACODE_API_KEY_4 }}
    - uses: actions/upload-artifact@v4
      if: success()
      with:
        name: veracode-policy-check-${{ github.event.repository.name }}
        path: output.txt
    - name: send a failure slack message
      if: failure()  && inputs.channel_id != 'NO_SLACK'
      uses: ministryofjustice/hmpps-github-actions/.github/actions/slack_failure_results@v0.5 # WORKFLOW_VERSION
      with:
        SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
        channel_id: ${{ inputs.channel_id }}
        input_file: output.txt